### PR TITLE
Don't let users play a tone equal or less than 0

### PR DESCRIPTION
**Pull request by KTibow**
Previously, this would have caused a crash.

### CODE REVIEW

**Review by FoamyGuy — APPROVED** [review]
I tested this change successfully with `Adafruit CircuitPython 6.2.0-beta.2 on 2021-02-11; Adafruit MagTag with ESP32S2`

I did not ever witness it raise an exception from a negative frequency value, it always seem to fail silently for me (No error, but also no sound played) 

This change dies fix it though by checking for negative value and sending a message to the user to let them know it needs to be positive.

Thanks for working on this fix!

**Comment by KTibow** [comment]
I found it hard crash for me:
image
image

**Comment by FoamyGuy** [comment]
@KTibow Ah I see. I was testing with negative values (I tried -10 and -100 at first) those seem to fail silently for me.

`0` specifically though does result in a hard crash and device reset for me as well.

Good catch! Thank you for finding this and submitting a fix!

**Review by makermelissa — APPROVED** [review]
Thanks for finding and fixing this.

**Pull request merged**
