### PR TITLE
Cache fonts for lower memory usage

### PR DESCRIPTION
**Pull request by makermelissa**

### CODE REVIEW

**Comment by makermelissa** [comment]
Test script I used:
```
import time
from adafruit_magtag.magtag import MagTag

magtag = MagTag()
magtag.add_text(
    text_font="Arial-Bold-12.bdf",
    text_position=(10, 10),
)
magtag.add_text(
    text_font="Arial-Bold-12.bdf",
    text_position=(10, 30),
)
magtag.add_text(
    text_font="Arial-Bold-12.bdf",
    text_position=(10, 50),
)
magtag.add_text(
    text_font="Arial-Bold-12.bdf",
    text_position=(10, 70),
)
magtag.set_text("Hello 1", auto_refresh=False)
magtag.set_text("Hello 2", 1, auto_refresh=False)
magtag.set_text("Hello 3", 2, auto_refresh=False)
magtag.set_text("Hello 4", 3)

print(magtag._fonts)
while True:
    pass
```

**Review by FoamyGuy — APPROVED** [review]
I tested this successfully with the example script above. I had a different font on hand (arial 16) and I also added a few `gc` checks and I am seeing reduced memory usage with the new version.

Looks good to me. Thanks for this efficiency boost!

**Comment by makermelissa** [comment]
I'm gonna merge this in. It'll be moved to PortalBase when I get some refactor PRs merged, so it doesn't matter too much.

**Comment by ladyada** [comment]
verified that its about 50% faster now!

**Pull request merged**
